<a href="https://colab.research.google.com/github/kally1218/pycharmproject/blob/main/limu_deep_learning/%E7%BA%BF%E6%80%A7%E4%BB%A3%E6%95%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

#标量的情况

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x**y #四则运算都一样

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [ ]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [ ]:
#用tensor的index访问元素
x[3]

tensor(3)

In [ ]:
len(x)

4

In [ ]:
x.shape #在一维的向量里指的是元素数量

torch.Size([4])

In [ ]:
#创建矩阵,有20个元素,形状为m*n
A = torch.arange(20).reshape(5, 4)
A


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [ ]:
#转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [ ]:
#as symmetric matrix, A = A.T
#构建一个矩阵
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [ ]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [ ]:
X = torch.arange(24).reshape(2, 3, 4) #高维tensor
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [ ]:
#用clone()复制矩阵
A = torch.arange(20, dtype = torch.float32).reshape(5, 4)
B = A.clone()
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [ ]:
A * B #按元素做乘积

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [ ]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape #对X中的所有元素都加a, 并且用shape查看是否形状会有所改变


(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [ ]:
#计算元素总和
x = torch. arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [ ]:
#和视频不一样,构造A矩阵的时候记得加上dtype的数据类型
A1 = torch.arange(20*2, dtype=torch.float32).reshape(2, 5, 4)
A, A.shape, A.sum() #求各种tensor总和


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 torch.Size([5, 4]),
 tensor(190.))

In [ ]:
#求A的第一个维度的和, 就把哪个维度变成0
#张量的 .sum(dim=...) 就是按某个“维度”方向压缩，对应：
#dim=0: 跨“块”（batch 维）
#dim=1: 跨“行”
#dim=2: 跨“列”
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [ ]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [ ]:
#多维求和,哪两个被同时压缩,shape就变成剩下的哪个维度
A.sum(axis=[0, 1]).shape

torch.Size([])

In [ ]:
#求均值的两种方式
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

In [ ]:
#求指定axis的均值
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [ ]:
#如何保持axis的数量不变
sum_A = A.sum(axis=1, keepdims=True)
sum_A
#对每行进行求和,保持axis还是5

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [ ]:
#用广播机制,求每行的均值
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [ ]:
#点积
#y是一个一维单位向量
y = torch.ones(4, dtype=torch.float32)
x, y ,torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [ ]:
#还有一种就是按照上面元素做各个乘法,然后求和
torch.sum(x * y)

tensor(6.)

In [ ]:
#矩阵和向量相乘,注意torch里面遇到矩阵向量乘法默认向量为列向量,虽然横着写
A.shape, x.shape, torch.mv(A,x) #torch.mv是 matrix-vector缩写

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [ ]:
B = torch.ones(4, 3) #矩阵乘法
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [ ]:
#求向量or矩阵的长度,这边求L2的范数 求平方和开根号
u= torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [ ]:
#求L1范数,求绝对值的和,常用
torch.abs(u).sum()

tensor(7.)

In [ ]:
#矩阵的范数叫做Frobenius norm, 是各个元素平方和的平方根
torch.norm(torch.ones(4,9)) #单位矩阵4*9的尺寸,36开根号

tensor(6.)